services:
  python:
    build:
      context: .
    network_mode: host
    #runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=$DISPLAY
      - XAUTHORITY=/tmp/.docker.xauth
      - JUPYTER_RUNTIME_DIR=/tmp/runtime
    ports:
      - 8888:8888
      - 5679:5679
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      #- ./in/notebooks:/tf/notebooks
      - ./out/logs:/content/logs
    deploy:
      resources:
        limits:
          memory: 7G
