services:
  python:
    build:
      context: .
    network_mode: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=$DISPLAY
      - XAUTHORITY=/tmp/.docker.xauth
      - JUPYTER_RUNTIME_DIR=/tmp/runtime
    ports:
      - 8888:8888
      - 5679:5679
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./out/logs:/content/logs
      - ./out/files:/content/files
    deploy:
      resources:
        limits:
          memory: 7G
